apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
namespace: instavote
images:
- name: dockeridjz/vote
  newTag: main-15b60b54-1644973989 # {"$imagepolicy": "flux-system:vote:tag"}
replicas:
- name: vote
  count: 4
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
configMapGenerator:
- name: vote
  literals:
  - OPTION_A=STAGING-v1
  - OPTION_B=DEV-v1
